// Shared by generation and review so both apply the same acceptance criteria.
// «Anatomía de una buena pregunta test» (QTH guide): what each part must do before a question is published.
export const QUESTION_ANATOMY = 'Anatomía de la pregunta (guía de QTH): el enunciado es claro, preciso, sin errores ortográficos ni gramaticales y sin ambigüedad, y pregunta una sola cosa; la respuesta correcta está justificada por el temario; los distractores son creíbles, pero claramente incorrectos para quien domina el temario; la explicación dice por qué la correcta es correcta y, cuando procede, por qué las otras no lo son; la referencia permite comprobar el contenido y defender la pregunta ante dudas o impugnaciones. Si una pregunta no puede justificarse con una fuente clara, no debe publicarse: la precisión es más importante que la creatividad.';
export const DISTRACTOR_POLICY = 'La respuesta correcta es la única opción que sale literalmente del temario. Las opciones incorrectas se inventan con sentido común y criterio: no tienen que aparecer en el temario. Deben pertenecer a la misma categoría que la respuesta (misma magnitud y unidad, mismo tipo de concepto), ser verosímiles para quien no domina el tema y quedar descartadas sin ambigüedad por la fuente. Si encaja, también sirve un dato que el temario da para otro contexto (en una pregunta sobre el nitrógeno, una propiedad del CO₂). Cuánto se parecen a la correcta lo decide el nivel. En las preguntas de cálculo, los distractores pueden ser resultados de errores típicos con los datos del enunciado (unidad equivocada, fórmula inversa, paso omitido). Ningún distractor puede contradecir el sentido común ni poder descartarse sin haber estudiado el tema. Ajusta su proximidad al nivel. En P los distractores deben poder descartarse fácilmente conociendo el dato, pero nunca sin conocerlo. Prohibido: opciones que contradigan el propósito del concepto (acelerar la combustión en un mecanismo de extinción), que se contradigan a sí mismas o que mezclen categorías ajenas (polvos en una pregunta de espumas). En F requieren precisión; en D pueden diferir en matices. Evita absurdos, ambigüedad y absolutos injustificados. Las cuatro opciones deben tener una longitud similar: entre la opción más larga y la más corta no puede haber más de 5 palabras de diferencia; las opciones «Todas son correctas» y «Ninguna es correcta» no cuentan para esta medida. Una misma evidencia puede justificar varios descartes.';

export const POSITION_POLICY = 'No uses referencias a letras o posiciones en enunciado, opciones ni explicación. Identifica las respuestas por su contenido; por ejemplo, «10 bar es el valor indicado; 8 bar corresponde a otro equipo». Las opciones de conjunto se redactan como «Todas son correctas.» o «Ninguna es correcta.», se admiten en F y D y, en P, solo cuando estén muy justificadas (ver la regla «opciones-de-conjunto»), deben referirse a las otras tres alternativas independientemente del orden y solo se admiten si hay una única respuesta seleccionable. No las combines con preguntas que pidan la INCORRECTA.';

// QTH guide, «Niveles de dificultad»: shared by generation and review so a question is written and judged by
// the same definition of its level.
export const DIFFICULTY_PRINCIPLE = 'La dificultad no debe depender de redactar mal la pregunta, sino de tres cosas: la profundidad del contenido, la similitud entre opciones y el nivel de dominio que exige al alumno.';
export const LEVEL_GUIDE = {
  PRINCIPIANTE: 'Nivel P (Principiante). Qué mide: estructura básica del tema, conceptos generales, títulos, clasificaciones simples y contenido superficial; el alumno piensa «esto lo puedo responder si he dado un par de vueltas al tema». Objetivo: asegurar que domina la base del tema, construir confianza y reforzar lo esencial (en los exámenes oficiales también hay preguntas de este nivel). Cómo deben ser: extraídas de la capa más superficial (títulos, subtítulos, definiciones básicas y clasificaciones generales); respondibles tras estudiar el tema un par de veces; enunciados breves y fáciles de entender; opciones incorrectas claramente descartables, con bastante distancia respecto a la correcta; fieles a la literalidad del texto oficial cuando se pregunte un dato o definición; sin trampas ni juegos de despiste. Qué evitar: enunciados largos, opciones demasiado parecidas, cambios mínimos de palabras que confundan, detalles muy escondidos y «Todas son correctas»/«Ninguna es correcta» salvo que esté muy justificado.',
  FACIL: 'Nivel F (Fácil / intermedia). Qué mide: mayor dominio del tema, memorización más fina, comprensión de conceptos y atención a respuestas parecidas; el alumno piensa «lo sé, pero tengo que leer bien porque hay opciones que se parecen». Objetivo: enseñar que no basta con haber leído el tema: hay que comprender, memorizar con precisión y diferenciar opciones parecidas. Cómo deben ser: pueden entrar en una capa más profunda del tema; exigen mayor dominio de conceptos, datos y relaciones; distractores relativamente parecidos a la correcta; datos numéricos cercanos entre sí si la fuente es clara; «Ninguna es correcta» si no genera ambigüedad; al menos una o dos opciones incorrectas descartables para quien ha estudiado bien; obligan a leer con calma y no responder por intuición; pueden trabajar comprensión y memorización a la vez. La duda que genera es útil solo si la pregunta está bien construida.',
  DIFICIL: 'Nivel D (Difícil). Qué mide: detalles, relaciones entre varios conceptos, aplicación práctica, enunciados más largos y trampas razonables; el alumno piensa «tengo que dominar el tema y aplicar lo estudiado con precisión». Objetivo: enseñar que siempre hay margen de mejora, mostrar detalles que pasan desapercibidos y entrenar para exámenes exigentes. Cómo deben ser: la trampa puede estar en el enunciado, no solo en las respuestas; pueden exigir cambios de unidades, cálculos, fórmulas o aplicación práctica; enunciados más largos pero comprensibles; pueden incluir información que no es necesaria para responder; opciones muy similares entre sí; pueden basarse en tablas largas, datos poco visibles o detalles que suelen pasar desapercibidos; pueden mezclar varios conceptos del mismo tema o de temas relacionados; exigen dominio real, no intuición; difíciles pero defendibles y no ambiguas. Qué evitar: confundir dificultad con mala redacción, varias interpretaciones posibles, distractores que también podrían defenderse como correctos, detalles imposibles de localizar o sin valor real para el examen, y trampas injustas que no miden conocimiento.',
};

// QTH guide, «Cómo construir buenas respuestas incorrectas»: a distractor is not absurd, but it cannot be debatable.
export const DISTRACTOR_GUIDE = 'Cómo construir los distractores (guía de QTH): un distractor no debe ser absurdo, pero tampoco discutible. Debe parecer razonable a quien no domina el tema, estar relacionado con el contenido preguntado, ser claramente incorrecto si se revisa la fuente oficial, tener una longitud y un estilo parecidos a la respuesta correcta, evitar pistas evidentes como «siempre», «nunca» o frases exageradas (salvo que sean parte real del contenido) y no introducir conceptos ajenos que confundan sin aportar valor. Solo la respuesta correcta tiene que salir literalmente del temario; los distractores se inventan con sentido común y criterio. Errores frecuentes: una opción demasiado absurda; la correcta mucho más larga o técnica que las demás; dos opciones que significan prácticamente lo mismo; dos respuestas que podrían ser correctas según la interpretación; palabras ambiguas como «normalmente», «aproximadamente» o «en general» sin justificar; y cambiar un dato sin comprobar que el cambio no se pueda defender.';

// QTH guide, «Cómo evitar preguntas impugnables», with the cases found in generated tests.
export const CONTESTABLE_CASES = 'una opción incorrecta que también podría defenderse (por ejemplo, en una pregunta de siglas o códigos, otra combinación que también es cierta); una explicación que reconoce que otra opción también vale; una opción parcialmente cierta (en las que piden la INCORRECTA, la marcada debe ser totalmente falsa y las otras tres totalmente verdaderas); una pregunta que depende de una probable errata del manual (por ejemplo, «estacionario» donde el sentido pide «estacional»); y una afirmación que contradice el conocimiento científico básico (por ejemplo, que la densidad de los sólidos no varía con la temperatura), que un alumno con formación podría impugnar aunque el manual la diga';

// A generated question gave «1080 calorías» as the result of 540 cal/g × 2.000 g and justified it with «the
// options are in thousands». The answer must be the exact result, in the unit it is written in.
export const CALCULATION_RULE = 'Preguntas de cálculo, fórmula o cambio de unidades: resuelve el cálculo paso a paso antes de escribir las opciones. La respuesta correcta es exactamente el resultado, con su unidad escrita (1.080.000 cal o 1.080 kcal, nunca 1080 calorías). No hay opciones «en miles» ni unidades implícitas: el número y la unidad de cada opción se leen tal como están escritos. Todas las opciones usan la misma unidad y el mismo formato, con punto de miles (540.000 cal, 1.080.000 cal). La explicación muestra la fórmula, la sustitución y el resultado, que debe ser el de la opción correcta.';

// Formats are counted for the test mix; generator and reviewer must classify them the same way.
export const FORMAT_DEFINITIONS = 'Definición de cada format (objetivo principal de la pregunta): DIRECTA, un dato, término o definición; CORRECTA, elegir la afirmación verdadera entre cuatro; INCORRECTA, elegir la falsa o lo que NO es; CLASIFICACION, tipos, clases, fases o elementos de una lista; CIFRA, recordar un valor numérico; FORMULA, aplicar una fórmula o conversión que aparece en el manual (temperaturas, porcentajes, proporciones de mezcla…) para obtener un resultado; preguntar el nombre de una fórmula química o qué fórmula corresponde a una sustancia NO es FORMULA; COMPARACION, diferenciar dos conceptos parecidos; TODAS_NINGUNA, la pregunta incluye «Todas son correctas.» o «Ninguna es correcta.».';

// Measured on the 690 teachers' questions (quality_sources/preguntas_testor): what makes ours look like theirs.
export const TEACHER_STYLE = {
  PRINCIPIANTE: 'Estilo de P (guía de QTH y preguntas de los profesores): enunciado directo y breve («¿Cómo se denomina…?», «¿Cuál es…?») o frase incompleta que terminan las opciones («Cuando hablamos del agua como agente extintor, debemos saber que al evaporarse su volumen aumenta…»). Opciones muy cortas: la mitad tiene 4 palabras o menos (un término, una cifra, un rango o una frase breve); solo 1 de cada 8 preguntas usa cuatro afirmaciones. Distractores: elementos hermanos de la misma lista o clasificación claramente distintos entre sí (otros mecanismos de extinción, otras clases de fuego, otros aditivos) o cifras y rangos del mismo formato bien separados de la correcta. En P NO uses cambios mínimos de palabras ni términos de forma parecida: la guía los reserva para F y D. Explicación breve (unas 40 palabras): la frase del manual que da la respuesta y, si la pregunta es de una lista o tabla, la lista o los valores completos para que se vea a qué corresponde cada distractor.',
  FACIL: 'Estilo de F según la guía de QTH («Lo sé, pero tengo que leer bien porque hay opciones que se parecen»): capa más profunda del tema que en P, memorización precisa y comprensión. Enunciados directos o frases incompletas y opciones cortas, pero con distractores relativamente parecidos a la correcta: cifras cercanas con el mismo formato («21 %.», «19 %.», «23 %.»), términos hermanos muy próximos y frases literales con una palabra clave cambiada. Al menos una o dos opciones deben poder descartarse por quien ha estudiado bien. Puede usarse «Ninguna es correcta.» si no genera ambigüedad. Explicación breve con la frase del manual; cuando ayuda, indica a qué corresponde cada distractor o corrige el dato cambiado en MAYÚSCULAS.',
  DIFICIL: 'Estilo de D (guía de QTH y preguntas de los profesores): enunciados más largos (unas 21 palabras), a veces un supuesto práctico («Supongamos que en una instalación…», «Nos encontramos en un incendio en planta R+7…») o un cálculo con los datos del enunciado, que puede incluir algún dato innecesario. Opciones de unas 10 palabras: cuatro afirmaciones con la misma plantilla en las que cambia un solo dato o relación (mayor/menor, encima/debajo, límite inferior/superior), la frase literal con una palabra clave cambiada (exotérmica/endotérmica), valores de filas vecinas de una tabla o resultados de errores típicos de cálculo (signo, decimal, factor). Explicación: la frase del manual con el dato cambiado corregido en MAYÚSCULAS y el erróneo entre paréntesis («con la misma INTENSIDAD (no velocidad)»), o el cálculo paso a paso.',
};
export const TEACHER_GENERAL_STYLE = 'Errores frecuentes que la guía de QTH manda evitar: la respuesta correcta mucho más larga o más técnica que las demás (en los profesores es la más larga solo en 1 de cada 6), dos opciones que significan prácticamente lo mismo, dos respuestas que podrían ser correctas según la interpretación, palabras ambiguas no justificadas («normalmente», «aproximadamente», «en general») y pistas como «siempre» o «nunca» que no estén en el contenido. No imites distractores absurdos que aparecen en algún ejemplo (colores sin relación, siglas inventadas, cifras de distinto orden de magnitud como 7, 17, 170 y 1.700) ni las combinaciones por letra («a) y b) son correctas»).';
