// Shared by generation and review so both apply the same acceptance criteria.
export const DISTRACTOR_POLICY = 'Las alternativas de contenido deben pertenecer a la misma categoría conceptual. Prefiere distractores que sean datos reales del mismo tema que el temario atribuye a otro contexto: otra sustancia, clase, fase, categoría, fila de tabla, equipo o procedimiento. Por ejemplo, en una pregunta sobre el nitrógeno, una propiedad que el temario da para el CO₂. Si no hay un dato real que encaje, se admite un distractor inventado solo si cumple todas estas condiciones: es verosímil para quien no domina el tema, pertenece a la misma categoría que la respuesta (misma magnitud y unidad, mismo tipo de concepto), no contradice el sentido común y la fuente permite descartarlo sin ambigüedad. En las preguntas de cálculo, los distractores pueden ser resultados de errores típicos con los datos del enunciado (unidad equivocada, fórmula inversa, paso omitido). Ningún distractor puede contradecir el sentido común ni poder descartarse sin haber estudiado el tema. Ajusta su proximidad al nivel. En P los distractores deben poder descartarse fácilmente conociendo el dato, pero nunca sin conocerlo. Prohibido: opciones que contradigan el propósito del concepto (acelerar la combustión en un mecanismo de extinción), que se contradigan a sí mismas o que mezclen categorías ajenas (polvos en una pregunta de espumas). En F requieren precisión; en D pueden diferir en matices. Evita absurdos, ambigüedad y absolutos injustificados. Las cuatro opciones deben tener una longitud similar: entre la opción más larga y la más corta no puede haber más de 5 palabras de diferencia; las opciones «Todas son correctas» y «Ninguna es correcta» no cuentan para esta medida. Una misma evidencia puede justificar varios descartes.';

export const POSITION_POLICY = 'No uses referencias a letras o posiciones en enunciado, opciones ni explicación. Identifica las respuestas por su contenido; por ejemplo, «10 bar es el valor indicado; 8 bar corresponde a otro equipo». Las opciones de conjunto se redactan como «Todas son correctas.» o «Ninguna es correcta.», se admiten en F y D y, en P, solo cuando estén muy justificadas (ver la regla «opciones-de-conjunto»), deben referirse a las otras tres alternativas independientemente del orden y solo se admiten si hay una única respuesta seleccionable. No las combines con preguntas que pidan la INCORRECTA.';

// Formats are counted for the test mix; generator and reviewer must classify them the same way.
export const FORMAT_DEFINITIONS = 'Definición de cada format (objetivo principal de la pregunta): DIRECTA, un dato, término o definición; CORRECTA, elegir la afirmación verdadera entre cuatro; INCORRECTA, elegir la falsa o lo que NO es; CLASIFICACION, tipos, clases, fases o elementos de una lista; CIFRA, recordar un valor numérico; FORMULA, aplicar una fórmula o conversión que aparece en el manual (temperaturas, porcentajes, proporciones de mezcla…) para obtener un resultado; preguntar el nombre de una fórmula química o qué fórmula corresponde a una sustancia NO es FORMULA; COMPARACION, diferenciar dos conceptos parecidos; TODAS_NINGUNA, la pregunta incluye «Todas son correctas.» o «Ninguna es correcta.».';

// Measured on the 690 teachers' questions (quality_sources/preguntas_testor): what makes ours look like theirs.
export const TEACHER_STYLE = {
  PRINCIPIANTE: 'Estilo de P (guía de QTH y preguntas de los profesores): enunciado directo y breve («¿Cómo se denomina…?», «¿Cuál es…?») o frase incompleta que terminan las opciones («Cuando hablamos del agua como agente extintor, debemos saber que al evaporarse su volumen aumenta…»). Opciones muy cortas: la mitad tiene 4 palabras o menos (un término, una cifra, un rango o una frase breve); solo 1 de cada 8 preguntas usa cuatro afirmaciones. Distractores: elementos hermanos de la misma lista o clasificación claramente distintos entre sí (otros mecanismos de extinción, otras clases de fuego, otros aditivos) o cifras y rangos del mismo formato bien separados de la correcta. En P NO uses cambios mínimos de palabras ni términos de forma parecida: la guía los reserva para F y D. Explicación breve (unas 40 palabras): la frase del manual que da la respuesta y, si la pregunta es de una lista o tabla, la lista o los valores completos para que se vea a qué corresponde cada distractor.',
  FACIL: 'Estilo de F según la guía de QTH («Lo sé, pero tengo que leer bien porque hay opciones que se parecen»): capa más profunda del tema que en P, memorización precisa y comprensión. Enunciados directos o frases incompletas y opciones cortas, pero con distractores relativamente parecidos a la correcta: cifras cercanas con el mismo formato («21 %.», «19 %.», «23 %.»), términos hermanos muy próximos y frases literales con una palabra clave cambiada. Al menos una o dos opciones deben poder descartarse por quien ha estudiado bien. Puede usarse «Ninguna es correcta.» si no genera ambigüedad. Explicación breve con la frase del manual; cuando ayuda, indica a qué corresponde cada distractor o corrige el dato cambiado en MAYÚSCULAS.',
  DIFICIL: 'Estilo de D (guía de QTH y preguntas de los profesores): enunciados más largos (unas 21 palabras), a veces un supuesto práctico («Supongamos que en una instalación…», «Nos encontramos en un incendio en planta R+7…») o un cálculo con los datos del enunciado, que puede incluir algún dato innecesario. Opciones de unas 10 palabras: cuatro afirmaciones con la misma plantilla en las que cambia un solo dato o relación (mayor/menor, encima/debajo, límite inferior/superior), la frase literal con una palabra clave cambiada (exotérmica/endotérmica), valores de filas vecinas de una tabla o resultados de errores típicos de cálculo (signo, decimal, factor). Explicación: la frase del manual con el dato cambiado corregido en MAYÚSCULAS y el erróneo entre paréntesis («con la misma INTENSIDAD (no velocidad)»), o el cálculo paso a paso.',
};
export const TEACHER_GENERAL_STYLE = 'Errores frecuentes que la guía de QTH manda evitar: la respuesta correcta mucho más larga o más técnica que las demás (en los profesores es la más larga solo en 1 de cada 6), dos opciones que significan prácticamente lo mismo, dos respuestas que podrían ser correctas según la interpretación, palabras ambiguas no justificadas («normalmente», «aproximadamente», «en general») y pistas como «siempre» o «nunca» que no estén en el contenido. No imites distractores absurdos que aparecen en algún ejemplo (colores sin relación, siglas inventadas, cifras de distinto orden de magnitud como 7, 17, 170 y 1.700) ni las combinaciones por letra («a) y b) son correctas»).';
